package config;

public interface DefaultTimeouts {
    int CLICK_TIMEOUT_SECONDS = 5;
    int PRESENCE_TIMEOUT_SECONDS = 5;
    int POLLING_WITH_REFRESH_TIMEOUT_SECONDS = 30;
    int REFRESH_TIMEOUT_SECONDS = 5;
    int SHORT_TIMEOUT_SECONDS = 1;
    int MEDIUM_TIMEOUT_SECONDS = 5;
    int LONG_TIMEOUT_SECONDS = 20;
    int PAUSE_BETWEEN_KEYS_MILLIS = 50;
    int PAUSE_BETWEEN_TRIES_MILLIS = 200;
    int PAUSE_BETWEEN_REFRESH_SECONDS = 5;
    int PAGE_LOAD_TIMEOUT_SECONDS = 20;
    int IMPLICIT_WAIT_TIMEOUT_MILLIS = 2000;
}
